### ISSUE TITLE
Question: How to add table from DB SQL like postgresql that data can query live data

### ISSUE THREAD

**Issue by ibnbay99** [nils-braun/dask-sql#106]
Because from the example in doc, right now `dask-sql` only support:
- dataframe from pandas & dask (data created just for first time)
- hive metastore (get cloud storage & hdfs file metadata and can get update live data) 
- cloud storage (can get update live data)

Any possibility right now to create table from `DB SQL` that data can query/get live data?
May be I miss read a doc.

Ty

**Comment by nils-braun** [comment]
That is a very good question and you nearly summarized the situation correctly. However, for dask dataframes (not for pandas dataframes), there is a small difference: the data is not "created" (or cached) just once, but actually, every time you run a calculation (if you do not persist or cache it on purpose). The reason is, that dask (in contrast to pandas), does not store any "real" data but only the computations which should be applied to the data (plus some metadata). Onle if you trigger it (e.g. with compute()), the data is fetched.

This means for `dask-sql`, that if you run
```python
df = ... some dask method, e.g. read_sql ...
c.create_table("table", df, persist=False)  # important: persist is True by default, but you do not want that here
c.sql("SELECT * FROM table").compute()
```
the data is only fetched the moment you run the `.compute()`.

**Comment by nils-braun** [comment]
As I did not hear back from you, I assume the question is solved.
