### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'Sarg[(0..1)]'

### ISSUE THREAD

**Issue by mschroederi** [nils-braun/dask-sql#175]
I'm experiencing issues when using `CASE` and checking whether a value is in a given range. The issue seems to occur when using `BETWEEN` as well as a manual range select.
In any case the execution fails with `ValueError: invalid literal for int() with base 10: 'Sarg[(0..1)]'`.
You can reproduce the error when using the code snippet below. Thanks!

```python
import dask
import dask_sql

import pandas as pd

df = pd.DataFrame({"A": [4.1] * 5})
data = dask.dataframe.from_pandas(df, npartitions=1)

sql_context = dask_sql.Context()
sql_context.create_table("data", data)

result = sql_context.sql(
    """
        SELECT
            CASE
                WHEN data.A > 0 AND data.A < 1 THEN 'in-between'
                ELSE 'out-of-range'
            END AS is_in_range
        FROM data
        """,
    return_futures=False,
)

print(result)
```

**Execution Environment**
Python 3.8.10
dask==2021.4.1
dask-sql==0.3.4

**Comment by nils-braun** [comment]
Thanks for the bug report @mschroederi and the very nice reproducible code!

The problem arises as `Calcite` (which is the SQL parser in dask-sql), transforms this SQL into 
```apache
LogicalProject(is_in_range=[CASE(SEARCH($0, Sarg[(0..1)]), 'in-between  ', 'out-of-range')])
  LogicalTableScan(table=[[schema, data]])
```
and both the `SEARCH` as well as its argument `Sarg[(0..1)` are not implemented in dask-sql (yet). Unfortunately, the exception is not very good - because unfortunately, it fails "at the wrong place"... (we should also fix this).

There are two possible solutions here: either "forbid" Calcite to transform it into a `SEARCH` (we need to check if this can be configured) or we need to implement both `SEARCH` as another call operator and a wrapper class for the Java instance of `Sarg`, to make it transportable to the dask workers (Java objects can not be serialized).

Would you like to have a look? I would be happy to help you get started and lead you with the first steps (with more information). Or shall I have a look?
