### ISSUE TITLE
Issue with create_table() 

### ISSUE THREAD

**Issue by timhdesilva** [nils-braun/dask-sql#186]
I'm running the following code:

```
import os
import numpy as np
import pandas as pd
import wrds
from dask import dataframe as dd
from dask.distributed import Client
client = Client()
client

noto = dd.read_csv('NOTO_equity_combined.csv') # 13GB
from dask_sql import Context
c = Context()
c.create_table('noto', noto)
```

Upon running ``c.create_table()``, a large process begins in my local client, which takes a few minutes. This is problematic because what I really want to do is a long sequence of pandas operations between reading in the csv and actually using ``create_table()`` for an SQL-like merge. Thus, when I have these operations in between, ``create_table()`` acts as if it's trying to ``.compute()`` my table, which is not going to be small enough to be in main memory yet. 

Am I doing something wrong here? I want to use ``dask-sql``, my workers keeping hitting their memory limit upon ``create_table()`` when I do the pandas operations in between.

**Comment by nils-braun** [comment]
Hi @timhdesilva!
Thanks for your question!
`create_table` will automatically persist (cache) the dataframe for faster access. That means it will start to compute everything (which is not the same as calling `compute`, as it will be loaded into the memory of the workers, but if you are using a local cluster as you have shown in your code, that is the same main memory).
You can turn it off using the setting `persist=False`.

However, at some point in time, Dask will need to load your data as otherwise it can not do any calculation on it. Maybe optimization will help, so it is definitely worth a try!

**Comment by timhdesilva** [comment]
Hi @nils-braun, thanks for the response!

If I use ``c.create_table()`` as above, following a few pandas dataframe calculations between reading the csv and calling it, my workers hit their memory limit as this executes. Does this mean I need to I need to find a way to reduce my data further, or will simply setting ``persist=False`` fix this? Also, how do I set ``persist=False``?  I don't see why I should be having a memory issue because the dataset is about 28GB before I do my computations that substantially reduce it's size, and I'm working on a laptop with 32GB RAM..

Thanks!

**Comment by nils-braun** [comment]
Hi @timhdesilva - multiple things play a role here and I am happy to give as much insights as I can - although I am also not able to list all of the factors:
* when you say "pandas dataframe calculations" I guess you referring to pandas-style dask calculations (like `df.groupby` or `df.sum` etc)? If this is the case, dask will build up a computation graph instead of doing the calculation. The calculation is executed on the first encounter of `.compute()` or `.persist()`.
* If you want, you can try it out by yourself: instead of giving the dataframe to `create_table`, call a `noto.persist()`. That will most likely also blow up your memory. 
* You can turn off the persiting in the call to `create_table`, by just passing `persist=False` to `create_table`, like `create_table("noto", noto, persist=False)` This You can find more information on the [docu](https://dask-sql.readthedocs.io/en/latest/pages/api.html#dask_sql.Context.create_table).

However, dask will need to load the data at some point into memory, otherwise it can not do any computations. 28 GB data with 32 GB of memory is actually really tight, actually you normally aim for data sizes ~10% of the memory (because every computation will add memory overhead, you need space for serialisation and deserialization etc.). How many partitions do you have? You can check this with `print(noto.npartitions)`. 

I think, that in the end this is less a problem with dask-sql, but more a problem with your data and the computation you are doing before that. To test this, could you maybe call a 
`len(noto)` before passing it to dask-sql and see, if it will already fail (this will trigger a calculation of all the data).

**Comment by timhdesilva** [comment]
Thanks for the helpful response @nils-braun. 

Most of the computations I run are trivial data cleaning tasks (renaming and creating variables), but the key computation is a ``.groupby().sum()`` operation that substantially reduces the size of the dataset. Immediately following this calculation is when I would like to then use ``.create_table()`` in order to perform an SQL like merge with a very small (62K rows x 10 columns) pandas dataframe that has been converted to a dask dataframe with one partition. The reason I need to do an SQL merge is because one of the merging criteria is that one variable is between two others. 

So I guess what I don't understand is whether there's a way for me to actually do this, given that the dataframe that's going into ``.create_table()`` is still very large. Since ``.groupby().sum()`` usually defaults to one partition, I use ``.groupby().sum(split_out = 50)``. I don't know exactly how big this dataframe is, but I don't need it in memory explicitly - I just want the SQL output, which should easily fit in memory. Is there any advice you can give me here?

Sorry for the dumb questions, but your help is much appreciated!

**Comment by nils-braun** [comment]
>  would this splitting the `.groupby().sum()` result into more partitions be more likely to help by reducing the amount of the data required in RAM at any point in time?

Yes, it will. Partitions are the only possibility for dask to parallelize. Dask is "smart" enough to see, that memory is already occupied and can spill the data partition-wise to disk (and load it from there later again). However, if you only have a single partition, dask can either use all the data or none - and there is no possibility for dask to store some of it temporarily on disk (to give room in main memory).

Did you test a call the `.persist()` before handing it to dask-sql? Did you run the `len` command? Did you already try to increase the number of partitions of the group by result? would be very interested in the results for further debugging.

**Comment by timhdesilva** [comment]
Hi @nils-braun! I was able to make this work by using setting ``split_out = 50`` in ``.groupby().sum()``! Thanks very much for the help!

**Comment by nils-braun** [comment]
Great! That is good to hear.
Thanks for reaching out!
