### ISSUE TITLE
connect to databricks cluster

### ISSUE THREAD

**Issue by raybellwaves** [nils-braun/dask-sql#83]
I'm taking a look at https://dask-sql.readthedocs.io/en/latest/pages/data_input.html#load-hive-data and i'm curious if a variant exists to connect to a databricks cluster (https://docs.microsoft.com/en-us/azure/databricks/integrations/bi/jdbc-odbc-bi) to extract tables/info from the Hive metastore.

https://stackoverflow.com/a/61806107/6046019 may also be relevant

**Comment by nils-braun** [comment]
That is a very interesting issue. Do you have - by any chance - a working databricks setup where you would be able to test this?

To be honest, I have never worked with Azure Databricks before, so I do not have any experience. However, I have found [this](https://kb.databricks.com/python/sql-in-python.html). In the code, there is the creation of a hive cursor described. This is also exactly what it needs as input to the `create_table` function. 

Concerning the stackoverflow link you shared: so far, I have always tested with a `pyhive.Cursor`. However, there is no reason it should not also work with a sqlalchemy connection. I have added a PR to also allow for these. 

So in my test setup with a "real" hive, both these code blocks work now:

```python
import sqlalchemy

cursor = sqlalchemy.create_engine("hive://localhost:10000").connect()

from dask_sql import Context

c = Context()
c.create_table("hh", cursor)

print(c.sql("SELECT * FROM hh").compute())
```

```
from pyhive.hive import connect

cursor = connect("localhost", 10000).cursor()

from dask_sql import Context

c = Context()
c.create_table("hh", cursor)

print(c.sql("SELECT * FROM hh").compute())
```

Would be super interesting, if this also works with the databricks cluster (looking at the code in the link I shared, I guess the `sqlalchemy`  solution you referenced is much simpler).
If you do not have the chance to test it, I can also try to set up a cluster on my own.

**Comment by raybellwaves** [comment]
Just making some notes here

Some common terms:

token = TOKEN # "xxxx" see https://docs.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/authentication#token-management
auth = "token:{}".format(token)
host = HOST # "adb-x.x.azuredatabricks.net
port = 443
database = DATABASE # "tmp"
http_path = "sql/protocolv1/o/x1/x2"
workspace_url = "x" # Name of the databricks instance
workspace_id = "x1" # x1 in http_path
cluster_id = "x2" # x2 in http_path

uri = "hive://token:{}@{}:{}/{}".format(token, host, port, database)

Get

```
  File "/Users/Ray/miniconda3/envs/test_env/lib/python3.8/site-packages/pyhive/hive.py", line 123, in __init__
    raise ValueError("Password should be set if and only if in LDAP or CUSTOM mode; "
ValueError: Password should be set if and only if in LDAP or CUSTOM mode; Remove password or use one of those modes
```

**Comment by nils-braun** [comment]
Sorry for the long pause, but let me summarize what we discussed verbally and what the current status is:
There are three problems that prevent this from working, which all need to be solved (does not need to be in this order):
* `dask-sql` expects the output of `DESCRIBE TABLE` to be in a certain format, which does not fit with the databricks one. This is easy to fix.
* `dask-sql` is relying on Dask to be able to actually read the content of the files. By default, these files are in "SequenceFile" format (special to the hadoop ecosystem). I have not found an easy solution to read those files (but maybe I am wrong). However, this is very easy to change on the user side, as creating the databricks/hive table with e.g. parquet format instead of sequence files is just a matter of `df.write.format("parquet").saveAsTable("tmp.df")` instead of `df.write.saveAsTable("tmp.df")`.
* Still, dask needs to access the data somehow - this is the issue you raised in intake/filesystem_spec#495.

I will take care that (1) is working. For (2) you can tell me, if the "fix" would be ok for you.
Would be very happy to see this, as it hopefully also gives benefits to the whole ecosystem!

**Comment by raybellwaves** [comment]
> easy to change on the user side, as creating the databricks/hive table with e.g. parquet format

I'll take a look here. I think `df.write.format("parquet").saveAsTable("tmp.df")` is optimal (?) in most cases anyway.

I may also investigate the file structure of [delta tables](https://docs.delta.io/latest/index.html) `df.write.format("delta").saveAsTable("tmp.df")`

**Comment by raybellwaves** [comment]
WIP:

Adding a couple steps in the table creation

```
df.write.format("parquet").saveAsTable("tmp.df_parquet_table")
df.write.format("delta").saveAsTable("tmp.df_delta_table")
```

Then check the formats locally:

Setup connection
```
import os
from pyhive import hive
from thrift.transport import THttpClient
import base64

conn = "https://{}/sql/protocolv1/o/{}/{}".format(
    os.getenv("DATABRICKS_HOST"),
    os.getenv("DATABRICKS_WORKSPACE"),
    os.getenv("DATABRICKS_CLUSTER_ID"),
)
auth = "token:{}".format(os.getenv("DATABRICKS_TOKEN"))

transport = THttpClient.THttpClient(conn)
authb = base64.standard_b64encode(auth.encode()).decode()
transport.setCustomHeaders({"Authorization": "Basic %s" % authb})
cursor = hive.connect(thrift_transport=transport, database="tmp").cursor()
```

**Comment by nils-braun** [comment]
Working in referencinf dbfs from dask here: https://github.com/intake/filesystem_spec/pull/504
Once this is finished, we can continue testing and maybe refining the dask-sql code to solve this issue :-)

**Comment by raybellwaves** [comment]
Awesome. I see it got merged! When the latest fsspec gets released we can pick this up.

**Comment by nils-braun** [comment]
The PR is included and the issue should therefore be fixed for now. If you are facing any problems, please re-open!

Related: #144
