### ISSUE TITLE
Boolean Where Clause Behavior

### ISSUE THREAD

**Issue by quasiben** [nils-braun/dask-sql#87]
Starting from a random timeseries table I played a bit with the `where` clause and got some unexpected results:

```python
from dask_sql import Context
import dask.datasets

df = dask.datasets.timeseries()
c = Context()
c.create_table("timeseries", df)
```

```python
In [26]: c.sql("SELECT *\nFROM timeseries AS q48\nWHERE True")
Out[26]:
Dask DataFrame Structure:
                   id    name        x        y
npartitions=30
2000-01-01      int64  object  float64  float64
2000-01-02        ...     ...      ...      ...
...               ...     ...      ...      ...
2000-01-30        ...     ...      ...      ...
2000-01-31        ...     ...      ...      ...
Dask Name: getitem, 210 tasks
```

However with `False`, `(0 = 1)`, and `(1 = 1)` there are failures:

```python
c.sql("SELECT *\nFROM timeseries AS q48\nWHERE (0 = 1)")

...
pandas/_libs/tslibs/timestamps.pyx in pandas._libs.tslibs.timestamps.Timestamp.__new__()
pandas/_libs/tslibs/conversion.pyx in pandas._libs.tslibs.conversion.convert_to_tsobject()
TypeError: Cannot convert input [False] of type <class 'numpy.bool_'> to Timestamp
```

The above is not totally unexpected -- a pandas dataframe cannot perform `df[True]`.  However, with SQL I believe `WHERE Boolean` is valid.  Is this reasonable to expect `dask-sql` to handle cleanly while dask/pandas do not?

**Comment by nils-braun** [comment]
Thank you very much for testing and making a bug report!
That is definitely reasonable. I think it should be doable by checking, if the filter is a scalar and just applying it directly on the dataframe. I needed to do something similar for the JOINS (because `a JOIN b ON True` is actually allowed) - so that should also be possible here. 
I have not checked, but I think the first one is optimized by Apache Calcite directly - therefore it is not a problem. 

The offending code is [here](https://github.com/nils-braun/dask-sql/blob/main/dask_sql/physical/rel/logical/filter.py#L29) and probably one could check this with something similar to [this](https://github.com/nils-braun/dask-sql/blob/main/dask_sql/physical/rel/logical/join.py#L158) - but I have not tested. I will only be able to work on this in a few days,  unfortunately.

**Comment by nils-braun** [comment]
Thanks again for the issue, @quasiben 
WIth the implemented fix I was able to run your examples. If you still see the issue, feel free to reopen.

**Comment by quasiben** [comment]
Thanks @nils-braun !
